### ISSUE TITLE
Diseño página crear Gastos

### ISSUE THREAD

**Issue by hendaniel** [JustPya/CrewFront#9]
## Diseño en Adobe XD

* [x] Crear en Adobe XD la página de agregar gasto
* [x] Debe tener los campos del modelo objeto JSON
* [x] Debe tener la aprobación de todos los miembros del equipo

**Comment by JustPya** [comment]
Revisión de diseño.
Adobe xd.


![image.png](https://images.zenhubusercontent.com/5b6cdd47084045741e744b72/20621b35-dbc8-4dc8-850b-53f6befc4fc8)
